name: test-cron
on:
  schedule:
    - cron: '* * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call Hello API route
        run: curl https://dealz.vercel.app/api/hello -H "webhook-secret: $SECRET_HEADER"
        env:
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
